README.markdown
doc/README-windows.md

doc: updated the copyright year to 2019.

---

t/sanity.t
util/configure
util/mirror-tarballs

feature: bundled the lua-tablepool library.

---

t/sanity.t
util/configure
util/mirror-tarballs

feature: bundled the lua-resty-signal and lua-resty-shell libraries.

---

t/sanity.t
util/configure

bugfix: we now build lua-resty-signal's shared lib component.

---

.travis.yml
t/Config.pm
t/sanity.t

travis: added travis-ci support.

---

t/sanity.t
util/mirror-tarballs

upgraded LuaJIT to 2.1-20190221.

---

Makefile

feature: Makefile: added a 'clean' target to remove build artifacts.

---

.travis.yml
Makefile
t/000-sanity.t

> I hereby granted the copyright of the changes in this pull request

tests: sanity.t: renamed to t/000-sanity.t and added '.' in lib path.

---

t/000-sanity.t
util/mirror-tarballs

The new version contains an option to disable forward slash escaping.

upgraded lua-cjson to 2.1.0.8rc1.

---

.travis.yml

> I hereby granted the copyright of the changes in this pull request

travis-ci: upgraded OpenSSL to 1.1.1f, 1.0.2q, 1.1.0l, and fixed older versions downloads.

---

t/000-sanity.t
util/mirror-tarballs

upgraded lua-resty-limit-traffic to 0.07

---

util/configure

bugfix: fixed a typo in configure.

---

t/000-sanity.t
util/mirror-tarballs

upgraded lua-resty-redis to v0.29

---

util/mirror-tarballs

upgraded lua-resty-websocket to v0.08rc1.

---

util/mirror-tarballs

upgraded lua-resty-mysql to 0.23rc1.

---

util/mirror-tarballs

upgraded ngx_stream_lua to v0.0.9rc3.

---

util/mirror-tarballs

upgraded ngx_lua to 0.10.18rc3.

---

t/000-sanity.t

tests: fixed tests to reflect component version bumps.

---

.travis.yml

style: remove useless trailing spaces.

---

util/mirror-tarballs

upgraded ngx_lua to 0.10.18rc4.

---

util/mirror-tarballs

upgraded lua-resty-core to 0.1.20rc3.

---

util/mirror-tarballs

upgraded ngx_lua to 0.10.18.

---

util/mirror-tarballs

upgraded ngx_stream_lua to v0.0.9.

---

util/mirror-tarballs

upgraded lua-resty-core to 0.1.20.

---

util/mirror-tarballs

upgraded resty-cli to 0.27.

---

util/mirror-tarballs

upgraded lua-resty-websocket to 0.08.

---

util/mirror-tarballs

upgraded ngx_lua to 0.10.19.

---

util/mirror-tarballs

upgraded lua-resty-core to 0.1.21.

---

util/mirror-tarballs

upgraded lua-resty-mysql to 0.23.

---

t/000-sanity.t

tests: fixed tests to nginx version bumps.

---

doc/LuaJIT-2.1/ext_ffi_api.pod
specs/openresty.spec

doc: fixed misspelling.

---

t/000-sanity.t
util/mirror-tarballs

upgraded lua-resty-memcached to v0.16rc1.

---

t/000-sanity.t
util/mirror-tarballs

upgraded lua-resty-signal to 0.03rc1.

---

t/000-sanity.t
util/mirror-tarballs

upgraded LuaJIT to 2.1-20210510.

---

util/build-win32.sh

win32: upgraded openssl to 1.1.1k.

---

t/000-sanity.t
util/mirror-tarballs

upgraded ngx_stream_lua to 0.0.10rc2.

---

.travis.yml

travis-ci: upgraded OpenSSL to 1.1.1k.

---

patches/nginx-1.19.9-privileged_agent_process.patch

add privileged_agent connections to set cycle connections

feature: add privileged_agent connections.

---

patches/nginx-1.19.3-privileged_agent_process_connections.patch
patches/nginx-1.19.9-privileged_agent_process.patch
patches/nginx-1.19.9-privileged_agent_process_connections.patch
util/mirror-tarballs

change: split privileged agent process connections patch.

---

util/build-win32.sh

win32: upgraded openssl to 1.1.1l.

---

.travis.yml

travis-ci: upgrade dist of travis-ci to ubuntu bionic.

---

.travis.yml

travis-ci: updated ftp.pcre.org to sourceforge mirror for pcre download.

---

util/mirror-tarballs

fix the echoed message when applying ssl_client_hello_cb_yield.patch

---

patches/nginx-1.21.4-no_pool.patch

bugfix: fixed typo in no-pool patch of 1.21.4.

---

util/mirror-tarballs

upgraded luajit to 2.1-20220111.

---

t/000-sanity.t

tests: fixed tests to reflect LuaJIT version bumps.

---

t/000-sanity.t
util/mirror-tarballs
util/ver

bumped version to 1.21.4.1rc2.

---

util/build-win32.sh

win32/win64: upgraded openssl to 1.1.1n.

---

t/000-sanity.t
util/mirror-tarballs

upgraded luajit to 2.1-20220411.

---

util/build-win32.sh

win32/win64: upgrade zlib to 1.2.12.

---

util/ver

bumped version to 1.21.4.1rc3.

---

t/000-sanity.t
util/mirror-tarballs
util/ver

bumped version to 1.21.4.1.

---

.travis.yml
util/build-win32.sh

* win32/win64: upgraded openssl to 1.1.1p.

ci: upgraded OpenSSL to 1.1.1p.

---

patches/nginx-1.21.4-privileged_agent_process_thread_pool.patch
patches/nginx-1.23.0-privileged_agent_process_thread_pool.patch

feature: add privileged agent thread pool

---

util/mirror-tarballs

bugfix: tarballs add privileged agent threadpool

---

t/000-sanity.t
util/mirror-tarballs
util/ver

bumped version to 1.21.4.2.

---

t/000-sanity.t
util/mirror-tarballs

new: bumped components version for openresty 1.21.4.2.

---

.travis.yml

tests: upgraded OpenSSL to 1.1.1s.

---

t/000-sanity.t
util/mirror-tarballs

upgraded lua-resty-core to 0.1.25rc2.

new: upgraded ngx_lua to 0.10.23rc2.

---

t/000-sanity.t
util/mirror-tarballs

* upgraded stream_ngx_lua to 0.0.12.
* upgraded srcache-nginx-module to 0.33.
* upgraded lua-resty-memcached to 0.17.
* upgraded lua-resty-mysql to 0.26.
* upgraded lua-resty-upload to 0.11.
* upgraded lua-resty-websocket to 0.10.
* upgraded lua-resty-core to 0.1.25.

new: upgraded ngx_lua to 0.10.23.

---

.travis.yml
t/000-sanity.t
util/mirror-tarballs
util/ver

bumped version to 1.21.4.2rc1.

---

.travis.yml
t/000-sanity.t
util/mirror-tarballs
util/ver

bumped ngx_lua to 0.10.24rc1, ngx_stream_lua to 0.0.13rc1, lua-resty-core to 0.1.26rc1.

---

t/000-sanity.t
util/mirror-tarballs

upgraded luajit2 to 2.1-20230410.

---

t/000-sanity.t
util/mirror-tarballs
util/ver

bumped ngx_lua to 0.10.25, lua-resty-core to 0.1.27.

---

patches/patch.2023.h2.txt
util/mirror-tarballs

bugfix: applied the patch for secrity advisory to NGINX cores (CVE-2023-44487).

---

t/000-sanity.t
util/mirror-tarballs
util/ver

feature: release openresty-1.25.3rc1.

---

util/build-win32.sh

win32: upgraded deps openssl to 1.1.1w and zlib to 1.3.

---

t/000-sanity.t
util/mirror-tarballs
util/ver

formal release 1.25.3.1.

---

.travis.yml
t/000-sanity.t

tests: fixed failed test introduced by commit ad33f56e911d.

---

patches/nginx-CVE-2024-24989.patch
patches/nginx-CVE-2024-24990.patch
util/mirror-tarballs
util/ver

bugfix: backport fixes for CVE-2024-24989 and CVE-2024-24990.

---

patches/nginx-1.27.0-balancer_pool_max_retry.patch

bugfix: respect max retry after using balancer pool

---

util/build-win32.sh

win32: upgraded deps zlib to 1.3.1.

---

t/000-sanity.t
util/mirror-tarballs

feature: bumped lua-resty-redis to 0.31.

---

t/000-sanity.t
util/mirror-tarballs

feature: update luajit to v20240815.

---

t/000-sanity.t
util/ver

feature: upgrade the nginx core to 1.27.1.

---

.travis.yml

feature: update nginx to v1.27.1.

---

t/000-sanity.t
util/build-win32.sh
util/configure

win32: update pcre to pcre2-10.44.

---

.travis.yml

tests: fixed ci.
